version: "3"
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    command: ["v2ray","-config=/etc/v2ray/config.json"]
    ports:
    # shadowsocks port
      - 443:443
      - 443:443/udp
    # http-proxy port
      - 2080:2080
      - 2080:2080/udp
    # dokodemo-door port
      - 22233:22233
      - 22233:22233/udp
    volumes:
      - ./v2config.json:/etc/v2ray/config.json
